Report test results

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,8 +61,16 @@ jobs:
       working-directory: src/Twilio.AspNet.Core.UnitTests/
      
     - name: (Twilio.AspNet.Core.UnitTests) Test
-      run: dotnet test --no-build
+      run: dotnet test --no-build --logger trx
       working-directory: src/Twilio.AspNet.Core.UnitTests/
+
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure() # run this step even if previous step failed
+      with:
+        name: Twilio.AspNet.Core.UnitTests
+        path: src/Twilio.AspNet.Core.UnitTests/TestResults/*.trx
+        reporter: dotnet-trx
       
     - name: (Twilio.AspNet.Core) Pack
       run: dotnet pack -c Release -o ..\..\
@@ -94,8 +102,16 @@ jobs:
       working-directory: src/Twilio.AspNet.Mvc.UnitTests/
       
     - name: (Twilio.AspNet.Mvc.UnitTests) Test
-      run: dotnet test --no-build
+      run: dotnet test --no-build --logger trx
       working-directory: src/Twilio.AspNet.Mvc.UnitTests/
+      
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure() # run this step even if previous step failed
+      with:
+        name: Twilio.AspNet.Mvc.UnitTests
+        path: src/Twilio.AspNet.Mvc.UnitTests/TestResults/*.trx
+        reporter: dotnet-trx
       
     - name: (Twilio.AspNet.Mvc) Pack
       run: dotnet pack -c Release -o ..\..\
@@ -104,7 +120,6 @@ jobs:
     - name: (Twilio.AspNet.Mvc) Upload Artifacts
       uses: actions/upload-artifact@v3
       with:
-        name: Twilio.AspNet.Mvc packages
         path: |
           Twilio.AspNet.Mvc.*.nupkg
           Twilio.AspNet.Mvc.*.snupkg
